export enum LogType {
    OnboardingCreate = 'Onboarding Create',
    OnboardingPlacer = 'Onboarding Placer',
    OnboardingDiplomatStart = 'Onboarding Diplomat Start',
    OnboardingDiplomatFinish = 'Onboarding Diplomat Finish',
    OnboardingObserver = 'Onboarding Observer',
    OnboardingDevelopment = 'Onboarding Development',
    ValidateArt = 'ValidateArt',
    ValidateArtGood = 'ValidateArt Good',
    ValidateArtBad = 'ValidateArt Bad',
    ValidateArtIllegitimate = 'ValidateArt Illegitimate',
    SuggestionCreated = 'Suggestion Created',
    SuggestionNoTags = 'Suggestion NoTags',
    SuggestionDuplicate = 'Suggestion Duplicate',
    SuggestionAppreciated = 'Suggestion Appreciated',
    SuggestionDisliked = 'Suggestion Disliked',
    SuggestionVote = 'Suggestion Vote',
    DiplomacyClaim = 'Diplomacy Claim',
    DiplomacyReportStart = 'Diplomacy Report Start',
    DiplomacyReportFinish = 'Diplomacy Report Finish',
    DiplomacyInvite = 'Diplomacy Invite',
}